# Generated by Django 2.2.1 on 2019-04-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='title',
            field=models.CharField(default='new Title', max_length=240),
            preserve_default=False,
        ),
    ]
