# Generated by Django 2.2.1 on 2019-04-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postmodel_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='author_email',
            field=models.EmailField(blank=True, max_length=240, null=True),
        ),
    ]
